server:
  port: 8888
  host: localhost

spring:
  cloud:
    config:
      server:
        git:
          uri: ${user_home}/pniel-cloud-client-repo
                #user_home system variable:
                #https://github.com/pnielab
                #or local git but clone it
                #C:\PNIEL_SPRING_CLOUD

